### ISSUE TITLE
Proposal: Add language folders to each workshop

### ISSUE THREAD

**Issue by w0mbat** [devoxx4kids/materials#49]
Some workshop folders are really crowded and its sometimes not trivial to find all materials for a language.
My proposal would be to add language subfolders into each workshop. If we agree on this, I would be willed to make the changes.

**Comment by karrasz** [comment]
That´s a good idea!

**Comment by arun-gupta** [comment]
+1

On Thu, Jun 11, 2015 at 12:19 PM, karrasz <notifications@github.com> wrote:

> That´s a good idea!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/devoxx4kids/materials/issues/49#issuecomment-111088521>
> .
>



-- 
http://blog.arungupta.me
http://twitter.com/arungupta

**Comment by devoxx4kids** [comment]
Sure.  No problem, so refactoring is needed from time to time ☺
Go ahead
Daniel

**Comment by w0mbat** [comment]
Please see pull-request: #52

**Comment by vorburger** [comment]
as https://github.com/devoxx4kids/materials/pull/52 has been merged, perhaps this issue should now be closed?
