### ISSUE TITLE
Minecraft readme missing build-and-run instructions

### ISSUE THREAD

**Issue by nmcl** [devoxx4kids/materials#56]
Going through https://github.com/devoxx4kids/materials/tree/master/workshops/minecraft and the first example (Chat Items) covers creating/editing files in Eclipse but then jumps straight to telling the player how they can try the mod out in the game. The missing piece is going from the edited files to a compiled version that the player starts up. Presumably it's just as simple as "press the green run arrow"?

**Comment by arun-gupta** [comment]
This instruction is conveyed during the workshop :) Send a PR?

**Comment by nmcl** [comment]
Done :)

**Comment by arun-gupta** [comment]
Merged
