### ISSUE TITLE
Problem with Minecraft ChatItems example

### ISSUE THREAD

**Issue by nmcl** [devoxx4kids/materials#57]
Following https://github.com/devoxx4kids/materials/tree/master/workshops/minecraft and have confirmed installation procedures have been followed. Added ChatItems.java and MainMod.java, with registered ChatItems as required in the example Readme.

Confirmed that the mod is being started when kicking off Minecraft from Eclipse ...

[17:37:39] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Example Mod, FMLFileResourcePack:MyMods

Part 2 of the Gameplay instructions states: "Type in any message that contains the word “potato”" but perhaps it's not really "any"? For instance:

/clear and a few other commands gives ... [17:41:06] [Client thread/INFO]: [CHAT] You do not have permission to use this command

I couldn't find a command that actually produced a potato. For instance /me <my player id> potato

**Comment by nmcl** [comment]
Starting with creative obviously removes the permission issue. Should definitely add that to the instructions.

**Comment by arun-gupta** [comment]
Any thing starting with / is a command. The gameplay requires to type a message instead which is `potato` as opposed `/me potato`.

**Comment by nmcl** [comment]
I know how to start a command ;) But /potato gives "Unknown command" too.

**Comment by arun-gupta** [comment]
That is expected because it needs to be a message, not a command. The game play says to type T to open up chat window and type the message which is different from command.

**Comment by nmcl** [comment]
Ah, my bad! Now if I had my 12 year old son with me he'd have found my mistake in seconds ;)
