### ISSUE TITLE
Simpler tool install

### ISSUE THREAD

**Issue by brianfromoregon** [devoxx4kids/materials#66]
Hi, wanted to pass along a simple recipe for JDK and eclipse install that you might like to adopt in your install instructions. If not, that's OK too!

To avoid the Oracle java installer and accompanying (and annoying!) Java Update popups I have manually extracted JDK8 windows install from their exe file, and then modified eclipse.ini to find it in a sibling directory so JAVA_HOME isn't required to start eclipse.
Those can be downloaded here: https://github.com/brianfromoregon/ForgeSetup/releases

I also plan to package forge in the same download with gradle pointed to the jdk so JAVA_HOME isn't required for gradle either.

**Comment by arun-gupta** [comment]
Thanks for sharing the setup. Is it legal to ship JDK and Eclipse bundled like this?

We need this to work for all flavors of Windows and Mac. Will you be able to support it?

**Comment by brianfromoregon** [comment]
Ooh good question is it legal... I do not know. 
Happy to support it yes but don't own a mac so I'd only be able to support Windows and Linux.

Looks like this may not work, sorry :(

Hey Arun just for fun check it out, making 3d shapes with turtle graphics API! A [Turtle](https://github.com/brianfromoregon/ForgeProject/blob/master/src/main/java/com/findrealhope/util/Turtle.java), a [Box](https://github.com/brianfromoregon/ForgeProject/blob/master/src/main/java/com/findrealhope/shapes/Box.java) with [JUnit test](https://github.com/brianfromoregon/ForgeProject/blob/master/src/test/java/com/findrealhope/shapes/BoxTest.java) and a [Bresenham 3d line](https://github.com/brianfromoregon/ForgeProject/blob/master/src/main/java/com/findrealhope/shapes/Line.java)

**Comment by arun-gupta** [comment]
@brianfromoregon do you want to submit another workshop for Turtle Graphics?

**Comment by brianfromoregon** [comment]
Sure, could use a little guidance on desired format, assumptions made about DevEnv, target audience, time length, etc. Granted, I attended your oscon 2015 session with your son so have a general feel for what type of experience to target.

**Comment by arun-gupta** [comment]
Sounds good, file another issue and lets discuss it there?
